/* DO NOT EDIT THIS FILE - it is machine generated */
#if __APPLE__
    #include "../jvm/darwin/jni.h"
#elif _WIN64
    #include "../jvm/windows/jni.h"
#endif

/* Header for class cn_yapeteam_agent_Agent */

#ifndef _Included_cn_yapeteam_agent_Agent
#define _Included_cn_yapeteam_agent_Agent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yapeteam_agent_Agent
 * Method:    loadNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_yapeteam_agent_Agent_loadNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
