/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yapeteam_yolbi_antileak_AntiLeak */

#ifndef _Included_cn_yapeteam_yolbi_antileak_AntiLeak
#define _Included_cn_yapeteam_yolbi_antileak_AntiLeak
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     cn_yapeteam_yolbi_antileak_AntiLeak
	 * Method:    crash
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_cn_yapeteam_yolbi_antileak_AntiLeak_crash
	(JNIEnv*, jobject);

	/*
	 * Class:     cn_yapeteam_yolbi_antileak_AntiLeak
	 * Method:    crash2
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_cn_yapeteam_yolbi_antileak_AntiLeak_crash2
	(JNIEnv*, jobject);

	/*
	 * Class:     cn_yapeteam_yolbi_antileak_AntiLeak
	 * Method:    getHwid
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_cn_yapeteam_yolbi_antileak_AntiLeak_getHwid
	(JNIEnv*, jobject);

	/*
	 * Class:     cn_yapeteam_yolbi_antileak_AntiLeak
	 * Method:    checkVM
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_cn_yapeteam_yolbi_antileak_AntiLeak_checkVM
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
