/* DO NOT EDIT THIS FILE - it is machine generated */
#if __APPLE__
    #include "../jvm/darwin/jni.h"
#elif _WIN64
    #include "../jvm/windows/jni.h"
#endif

/* Header for class cn_yapeteam_injector_na */

#ifndef _Included_cn_yapeteam_injector_na
#define _Included_cn_yapeteam_injector_na
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yapeteam_injector_Utils
 * Method:    injectDLL
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_yapeteam_injector_Utils_injectDLL
        (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
