/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jvm/windows/jni.h"
/* Header for class cn_yapeteam_injector_Main */

#ifndef _Included_cn_yapeteam_injector_Main
#define _Included_cn_yapeteam_injector_Main
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_cn_yapeteam_injector_Main_login
  (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT jboolean JNICALL Java_cn_yapeteam_injector_Main_active
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
